# Tip: Requesting /herp_alias?test=1 is good test of ordered, chained redirects
# and shows non-regexp "from" requires an exact match
# by not prefix matching fourth rule's "from" value '/test'
# against redirected '/test/1'
-
    method:     rewrite
    from:       /herp_alias
    to:         /herp
-
    method:     r301
    from:       /herp
    to:         /derp
    options:
        host:   localhost
        method: GET
        scheme: http
-
    method:     r302
    from:       !ruby/regexp '/^\/.+\?test=(.+)/i'
    to:         /test/$1
    options:
        no_qs:  1
-
    method:     r303
    from:       /test
    to:         /testyourmight
-
    method:     r307
    from:       !ruby/regexp '/^\/warp\/[1-9]$/i'
    to:         /blackhole
    options:
        not:    !ruby/regexp '/^\/warp\/[7-9]$/i'
-
    method:     r308
    from:       /oldpostpath
    to:         /newpostpath

