# Tip: Requesting /herp?test=1 is a good test of ordered, chained redirections
# and shows non-regexp "from" requires an exact match & doesn't prefix match
# with third rule's "from" '/test' not matching redirected '/test/1'
-
    method:     r301
    from:       /herp
    to:         /derp
    options:
        host:   localhost
        method: GET
        scheme: http
-
    method:     r302
    from:       !ruby/regexp '/^\/.+\?test=(.+)/i'
    to:         /test/$1
    options:
        no_qs:  1
-
    method:     r303
    from:       /test
    to:         /testyourmight
-
    method:     rewrite
    from:       /about_alias
    to:         /about
-
    method:     r307
    from:       !ruby/regexp '/^\/warp\/[1-9]$/i'
    to:         /blackhole
    options:
        not:    !ruby/regexp '/^\/warp\/[7-9]$/i'

